"""Tests for `noxuslab._workflow` (the local-file primitive)."""

from pathlib import Path

import pytest

from noxuslab._workflow import (
    LocalWorkflow,
    check_uuid,
    extract_source_id,
    is_uuid,
)
from noxuslab.errors import BadFile

_OK = "11111111-2222-3333-4444-555555555555"


def test_is_uuid_accepts_canonical():
    assert is_uuid(_OK)


def test_is_uuid_rejects_garbage():
    assert not is_uuid("not-a-uuid")


def test_check_uuid_raises_on_garbage():
    with pytest.raises(BadFile):
        check_uuid("nope")


def test_extract_source_id_finds_provenance():
    src = f"# generated by `noxuslab pull` from {_OK} @ 2026\nx = 1\n"
    assert extract_source_id(src) == _OK


def test_extract_source_id_returns_none_when_absent():
    assert extract_source_id("just code\n") is None


def test_local_workflow_load_missing_file_raises(tmp_path: Path):
    with pytest.raises(BadFile, match="not found"):
        LocalWorkflow.load(tmp_path / "ghost.py")


def test_local_workflow_load_captures_provenance(tmp_path: Path):
    p = tmp_path / "flow.py"
    p.write_text(
        f"# generated by `noxuslab pull` from {_OK} @ 2026\nwf = object()\n",
        encoding="utf-8",
    )
    lw = LocalWorkflow.load(p)
    assert lw.provenance_id == _OK
    assert lw.path == p


def test_local_workflow_execute_returns_wf(tmp_path: Path):
    p = tmp_path / "flow.py"
    p.write_text(
        "class W:\n    nodes = [1]\n    edges = []\nwf = W()\n",
        encoding="utf-8",
    )
    wf = LocalWorkflow.load(p).execute()
    assert getattr(wf, "nodes", None) == [1]


def test_local_workflow_execute_raises_when_var_missing(tmp_path: Path):
    p = tmp_path / "flow.py"
    p.write_text("x = 1\n", encoding="utf-8")
    with pytest.raises(BadFile, match="no `wf` defined"):
        LocalWorkflow.load(p).execute()


def test_local_workflow_execute_strips_trailing_save(tmp_path: Path):
    """The trailing `print(c.workflows.save(wf).id)` is removed before exec."""
    p = tmp_path / "flow.py"
    p.write_text(
        "class W:\n    nodes = []\n    edges = []\nwf = W()\nc = None\n"
        "print(c.workflows.save(wf).id)\n",
        encoding="utf-8",
    )
    # Without the strip this would AttributeError on `None.workflows`.
    wf = LocalWorkflow.load(p).execute()
    assert wf is not None


def test_local_workflow_execute_namespace_returns_full_dict(tmp_path: Path):
    p = tmp_path / "agent.py"
    p.write_text(
        "agent_name = 'a'\nagent_id = 'b'\nagent_settings = object()\n",
        encoding="utf-8",
    )
    ns = LocalWorkflow.load(p).execute_namespace()
    assert ns.get("agent_name") == "a"
    assert ns.get("agent_id") == "b"
    assert ns.get("agent_settings") is not None
