"""Local-file primitive for workflows and agents.

One place that knows how to:

- read a Python file from disk,
- extract its provenance id (the source workflow id written by `pull`),
- load the file via `runpy.run_path` with the SDK `Client` stubbed so
  no network call happens during the load,
- normalise common errors into `BadFile`.

Replaces the duplicated `Client-stub + runpy` blocks that previously
lived in `cli.cmd_push`, `cli.cmd_diff --visual`, `cli._load_agent_file`,
`fmt.py`, and `runner.py`. Adding a sixth caller is now one line.

Why this lives here (and not in `codegen.py`): codegen renders Python
*from* a `WorkflowDefinition`; this module loads Python *into* one.
They are inverse operations and share no state, so they stay separate.
"""

from __future__ import annotations

import contextlib
import re
import runpy
from collections.abc import Iterator
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from noxuslab.errors import BadFile

_UUID = re.compile(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$")
_PROVENANCE = re.compile(
    r"^#\s*generated by `noxuslab pull` from "
    r"([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})\b",
    re.MULTILINE,
)
# The trailing `print(c.workflows.save(wf).id)` line in pulled files is
# stripped before exec so dry-run / fmt / replay never double-save.
_TRAILING_SAVE = re.compile(
    r"^\s*print\(c\.workflows\.save\([^)]*\)\.id\)\s*$",
    re.MULTILINE,
)


def is_uuid(s: str) -> bool:
    """Return True if `s` matches a canonical UUID v4 string."""
    return bool(_UUID.match(s.lower()))


def check_uuid(s: str) -> None:
    """Raise `BadFile` if `s` is not a UUID."""
    if not is_uuid(s):
        raise BadFile(f"not a uuid: {s}")


def extract_source_id(text: str) -> str | None:
    """Return the source workflow id from a pulled file's header, or None."""
    m = _PROVENANCE.search(text)
    return m.group(1) if m else None


@contextlib.contextmanager
def _stubbed_sdk_client() -> Iterator[None]:
    """Replace `noxus_sdk.client.Client` with a no-op stub during a block.

    The stub is a single class whose every attribute access yields a
    callable returning None. That covers `Client(...)`, `client.workflows`,
    `client.agents`, `client.knowledge_bases`, etc., without actually
    making network calls during a `runpy.run_path` load.
    """
    import noxus_sdk.client as _sdk

    real = _sdk.Client

    class _Stub:
        def __init__(self, *_a: Any, **_k: Any) -> None:
            self.nodes: list[Any] = []
            self.workflows = self
            self.agents = self
            self.knowledge_bases = self

        def __getattr__(self, _name: str) -> Any:
            return lambda *_a, **_k: None

    _sdk.Client = _Stub  # type: ignore[assignment]
    try:
        yield
    finally:
        _sdk.Client = real  # type: ignore[assignment]


@dataclass(frozen=True)
class LocalWorkflow:
    """A workflow Python file on disk: text, provenance, sandboxed loader.

    Construct with `LocalWorkflow.load(path)`. Use `.execute()` to obtain
    the live `WorkflowDefinition` object the file builds. The loader runs
    the file in a sandboxed namespace with the SDK `Client` stubbed so
    the file can be inspected without saving anything to the platform.
    """

    path: Path
    text: str
    provenance_id: str | None

    @classmethod
    def load(cls, path: str | Path) -> LocalWorkflow:
        """Read `path` from disk; raise `BadFile` if missing."""
        p = Path(path)
        if not p.is_file():
            raise BadFile(f"not found: {p}")
        text = p.read_text(encoding="utf-8")
        return cls(path=p, text=text, provenance_id=extract_source_id(text))

    def execute(self, *, var: str = "wf") -> Any:
        """Execute the file in a stubbed namespace and return `var`.

        Strips the trailing `print(c.workflows.save(wf).id)` line so
        loading a file pulled via `noxuslab pull` is a no-op on the
        server. Raises `BadFile` if `var` is not defined after the run.
        """
        cleaned = _TRAILING_SAVE.sub("", self.text)
        tmp = self.path.with_suffix(".__noxuslab_load.py")
        tmp.write_text(cleaned, encoding="utf-8")
        try:
            with _stubbed_sdk_client():
                ns = runpy.run_path(str(tmp), run_name="_noxuslab_load")
        finally:
            tmp.unlink(missing_ok=True)
        wf = ns.get(var)
        if wf is None:
            raise BadFile(f"{self.path}: no `{var}` defined")
        return wf

    def execute_namespace(self) -> dict[str, Any]:
        """Execute the file and return the full namespace (for agent files).

        Agents need three top-level variables (`agent_name`, `agent_id`,
        `agent_settings`), so the caller wants the whole dict, not just
        `wf`. Same sandbox semantics as `.execute()`.
        """
        tmp = self.path.with_suffix(".__noxuslab_load.py")
        tmp.write_text(self.text, encoding="utf-8")
        try:
            with _stubbed_sdk_client():
                return runpy.run_path(str(tmp), run_name="_noxuslab_load")
        finally:
            tmp.unlink(missing_ok=True)
