"""Render a Noxus `Agent` to a self-contained Python file.

The output mirrors `noxuslab.codegen` for workflows: a single script that
re-creates (or updates) the agent on `noxuslab agents push <file>`.

Round-trip contract:
- `agent_to_python(agent)` → `noxuslab agents push <file>` → equivalent agent.
- `--source-id` (auto-set by `agents pull`) makes push behave as an update;
  delete the line to force a new agent.
"""

from __future__ import annotations

import json
from datetime import UTC, datetime
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from noxus_sdk.resources.assistants import Agent


_HEADER = '''#!/usr/bin/env python
# generated by `noxuslab agents pull` from {source} @ {ts}
"""Push back via: noxuslab agents push <this-file>"""

import json
import os

from noxus_sdk.client import Client
from noxus_sdk.resources.conversations import ConversationSettings

c = Client(api_key=os.environ["NOXUS_API_KEY"])

agent_name = {name!r}
agent_id = {agent_id!r}  # remove this line to force creating a NEW agent

# Settings are serialised as JSON so the file is diff-friendly.
agent_settings = ConversationSettings.model_validate(json.loads("""\\
{settings}
"""))

if __name__ == "__main__":
    if agent_id:
        print(c.agents.update(agent_id, name=agent_name, settings=agent_settings).id)
    else:
        print(c.agents.create(agent_name, agent_settings).id)
'''


def agent_to_python(agent: Agent, *, source_id: str | None = None) -> str:
    """Render an `Agent` resource to standalone Python source.

    `source_id` is embedded as `agent_id` so push performs an update.
    Pass `None` (or remove the line in the file) to create a new agent.
    """
    settings_dict = agent.definition.model_dump(mode="json", exclude_none=True)
    # `json.dumps` produces a deterministic, diff-friendly representation that
    # `ConversationSettings.model_validate` accepts unchanged.
    settings_lit = json.dumps(settings_dict, indent=4, sort_keys=True)
    return _HEADER.format(
        source=source_id or agent.id,
        ts=datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ"),
        name=agent.name,
        agent_id=source_id or agent.id,
        settings=settings_lit,
    )
