"""Workflow file formatter.

`noxuslab fmt <file>` runs the file in an isolated namespace, extracts its
`wf` variable, and rewrites the file with the canonical Python form produced
by `workflow_to_python`. This eliminates spurious diffs caused by node order,
edge order, kwarg order, or hand-edited whitespace.

It is the workflow analogue of `ruff format` for `noxuslab` files. Pure
local — no network calls.

Modes:
- default: rewrite file in place (no-op if already canonical)
- `--check`: exit 1 if file would be rewritten, 0 otherwise (CI-friendly)
- `--diff`: print unified diff to stdout, do not write

Multiple files can be passed; exit code is the OR of per-file outcomes.
"""

import difflib
import re
import runpy
import sys
from pathlib import Path

from noxuslab.codegen import workflow_to_python
from noxuslab.errors import BadFile

# Strip the trailing print-id line so we don't execute the live save during fmt.
_SAVE_RE = re.compile(r"^\s*print\(c\.workflows\.save\([^)]*\)\.id\)\s*$", re.MULTILINE)
# Find the source-id from the provenance header so the rewrite preserves it.
_PROV_RE = re.compile(r"^# generated by `noxuslab pull` from (\S+)", re.MULTILINE)


def _load_wf(path: Path):
    """Run the file in isolation, return (wf, original_source).

    `Client` is monkey-patched to a stub during the run because fmt does not
    need a real connection — only the `wf` variable is consumed downstream.
    """
    src = path.read_text(encoding="utf-8")
    safe = _SAVE_RE.sub("", src)
    tmp = path.with_suffix(".__noxuslab_fmt.py")
    tmp.write_text(safe, encoding="utf-8")

    import noxus_sdk.client as _sdk_client

    real_client = _sdk_client.Client

    class _StubClient:
        def __init__(self, *_a, **_k):
            self.nodes = []

        def __getattr__(self, _name):
            return lambda *a, **k: None

    _sdk_client.Client = _StubClient  # type: ignore[assignment]
    try:
        ns = runpy.run_path(str(tmp), run_name="_noxuslab_fmt")
    finally:
        _sdk_client.Client = real_client  # type: ignore[assignment]
        tmp.unlink(missing_ok=True)
    wf = ns.get("wf")
    if wf is None:
        raise BadFile(f"{path}: no `wf` WorkflowDefinition variable found")
    return wf, src


def _canonical(path: Path) -> tuple[str, str]:
    """Return (current_source, canonical_source) for the file."""
    wf, src = _load_wf(path)
    m = _PROV_RE.search(src)
    canonical = workflow_to_python(wf, source_id=m.group(1) if m else None)
    return src, canonical


def fmt_one(path: Path, *, check: bool, show_diff: bool) -> int:
    """Format a single file. Returns 0 if unchanged, 1 if changed (or would change)."""
    if not path.is_file():
        raise BadFile(f"not found: {path}")
    src, canonical = _canonical(path)
    if src == canonical:
        return 0
    if show_diff:
        diff = difflib.unified_diff(
            src.splitlines(keepends=True),
            canonical.splitlines(keepends=True),
            fromfile=str(path),
            tofile=f"{path} (canonical)",
            n=3,
        )
        sys.stdout.writelines(diff)
        return 1
    if check:
        print(f"would reformat: {path}")
        return 1
    path.write_text(canonical, encoding="utf-8")
    print(f"reformatted: {path}")
    return 1


def fmt(paths: list[str], *, check: bool = False, show_diff: bool = False) -> int:
    """Format every path. Exit code is 1 if any file was (or would be) reformatted."""
    if not paths:
        raise BadFile("no files provided")
    rc = 0
    for p in paths:
        rc |= fmt_one(Path(p), check=check, show_diff=show_diff)
    return rc
