line-length = 100
target-version = "py310"

[lint]
select = [
  "E", "F", "W",
  "I",
  "B",
  "UP",
  "SIM",
  "S",
  "RET",
  "PTH",
]
ignore = [
  "E501",
  "S101",
]

[lint.per-file-ignores]
"conftest.py" = ["S"]
"*/*/tests/**" = ["S", "B011"]
"*/*/test_fixtures/**" = ["E501"]
"*/*/workflows/**" = ["E402", "F401"]

[format]
quote-style = "double"
